---
- name: Collect IOS Facts and Configure Logging Buffer
  hosts: virtual_routers
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Collect IOS version information
      ios_command:
        commands: show version
      register: ios_version

    - name: Display IOS version
      debug:
        var: ios_version.stdout

    - name: Gather information about L3 interfaces
      ios_command:
        commands: show interfaces
      register: l3_interfaces

    - name: Display L3 interfaces information
      debug:
        var: l3_interfaces.stdout

    - name: Configure logging buffer size
      ios_config:
        lines:
          - logging buffered 5000
