pipeline {
    agent any
    
    stages {
        stage('Prepare') {
            steps {
                git branch: 'main', url: 'https://github.com/MAGS-GH/Devasc_Skills_MAGSMercantec'
            }
        }
        stage('Docker build, Docker run') {
            steps {
                script {
                    docker.build('apache_custom', '-f Devasc_Skills/Task-3-Docker/Task3.dockerfile .')
                    docker.image('apache_custom').run('-d -p 8088:8088 --name apache_container')
                }
            }
        }
        stage('Test') {
            steps {
                sh 'sleep 10'
                sh 'curl http://localhost:8088'
            }
        }
    }
}
